export const weatherImages = {
  "Partly Cloudy ": require("./assets/partlycloudy.png"),
  "Partly cloudy": require("./assets/partlycloudy.png"),
  "Moderate rain": require("./assets//moderaterain.png"),
  "Patchy rain nearby": require("./assets/moderaterain.png"),
  Sunny: require("./assets/sunAsset.png"),
  Clear: require("./assets/sunAsset.png"),
  "Overcast ": require("./assets/cloud.png"),
  "Cloudy ": require("./assets/cloud.png"),
  "Light rain": require("./assets/moderaterain.png"),
  "Light drizzle": require("./assets/moderaterain.png"),
  "Moderate rain at times": require("./assets/moderaterain.png"),
  "Heavy rain": require("./assets/heavyrain.png"),
  "Heavy rain at times": require("./assets/heavyrain.png"),
  "Moderate or heavy freezing rain": require("./assets/heavyrain.png"),
  "Moderate or heavy rain shower": require("./assets/heavyrain.png"),
  "Moderate or heavy rain with thunder": require("./assets/heavyrain.png"),
  Mist: require("./assets/mist.png"),
  other: require("./assets/moderaterain.png"),
};
